from debian:bookworm-slim
run apt update -y
run apt install -y python3 python3-pip python3-notebook
workdir /notebook
cmd ["jupyter", "notebook", "--allow-root", "--ip", "0.0.0.0", "--no-browser"]
expose 8888